static const char black[]       = "#1e222a";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#61afef";  // focused window border
static const char green[]       = "#7EC7A2";
static const char red[]         = "#e06c75";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#EBCB8B";
static const char pink[]        = "#c678dd";
static const char col_borderbar[]  = "#1e222a"; // inner border

static const char col_bg[]          = "#1a1b26";
static const char col_dark[]        = "#16161E";
static const char col_fg[]          = "#a9b1d6";
static const char col_black[]       = "#32344a";
static const char col_red[]         = "#f7768e";
static const char col_green[]       = "#9ece6a";
static const char col_yellow[]      = "#e0af68";
static const char col_blue[]        = "#7aa2f7";
static const char col_magenta[]     = "#ad8ee6";
static const char col_cyan[]        = "#449dab";
static const char col_white[]       = "#787c99";
static const char col_br_black[]    = "#444b6a";
static const char col_br_red[]      = "#ff7a93";
static const char col_br_green[]    = "#b9f27c";
static const char col_br_yellow[]   = "#ff9e64";
static const char col_br_blue[]     = "#7da6ff";
static const char col_br_magenta[]  = "#bb9af7";
static const char col_br_cyan[]     = "#0db9d7";
static const char col_br_white[]    = "#acb0d0";
